apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: iot-events

resources:
- ../../base/

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: iot-events
  path: patches/image.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: iot-events
  path: patches/deployment.yaml
