apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: iot-events
    includeSelectors: true

resources:
- ../../base/

patches:
- target:
    kind: Deployment
    name: iot-events
  path: patches/image.yaml
