apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    opentelemetry: enabled
  name: iot-events
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - env:
            - name: CONTROL_PORT
              value: "8000"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: iot-events
                  resource: limits.memory
            - name: RABBITMQ_HOST
              value: rabbitmq
          image: ghcr.io/diwise/iot-events:changeme
          imagePullPolicy: IfNotPresent
          name: iot-events
          ports:
            - containerPort: 8080
              name: default-port
              protocol: TCP
            - containerPort: 8000
              name: control-port
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 100Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: control-port
          readinessProbe:
            httpGet:
              path: /readyz
              port: control-port
          livenessProbe:
            httpGet:
              path: /livez
              port: control-port
          volumeMounts:
            - name: conf-volume
              mountPath: /opt/diwise/config
              readOnly: true
      serviceAccountName: iot-events
      volumes:
        - name: conf-volume
          configMap:
            name: iot-events-cfg-cm
